version: '3'
services:
  database:
    container_name: atmlocator_database
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=atm123
      - POSTGRES_DB=atmlocator
    volumes:
    - postgres-data:/var/lib/postgresql/data
    ports:
    - 5454:5432
  atmlocator:
    depends_on:
      - database
    image: atmlocator.jar
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/atmlocator
    ports:
      - "8080:8080"
  prometheus:
    image: prom/prometheus:v2.35.0
    network_mode: host
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./data/prometheus/config:/etc/prometheus/
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"
    ports:
      - 9090:9090

volumes:
  postgres-data:
    driver: local
